Add eseal theme
oh-my-fish/packages-main pull request #168
Opened 2022-05-01 21:27 UTC by isinyaaa

2022-06-30 22:22 UTC, derekstavis approved these changes

2022-06-30 22:22 UTC, derekstavis commented on packages/eseal
> +type = plugin
This should be `theme` instead

2022-06-30 22:23 UTC, derekstavis requested changes
Approved mistakenly first. Please make the requested change before we can merge

2022-07-04 10:39 UTC, scorphus requested changes

2022-07-04 10:39 UTC, scorphus commented on packages/eseal
> +type = plugin
```suggestion
type = theme
```

2022-07-04 10:43 UTC, scorphus approved these changes
@isinyaaa it would be helpful adding a screenshot of eseal 🙂

2022-07-15 21:56 UTC, isinyaaa commented
> @isinyaaa it would be helpful adding a screenshot of eseal 🙂

okay, will do :)

2022-07-16 15:08 UTC, isinyaaa commented
@scorphus you mean adding it here? I don't see any way to add it to the repo.

anyway, there you go:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/39812919/179360665-85b95ee2-cb82-46b8-9880-3f33c4dc49da.png">

2023-02-13 07:31 UTC, derekstavis approved these changes

2023-02-13 07:32 UTC, merged